# Generated by Django 4.0.6 on 2024-03-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_curso', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20)),
                ('apresentacao', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('competencias', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_disciplina', models.CharField(max_length=50)),
                ('ano', models.IntegerField(verbose_name='Ano da disciplina')),
                ('semestre', models.IntegerField(verbose_name='Semeste da disciplina')),
                ('ects', models.IntegerField(verbose_name='Número de ects')),
                ('curricularIUnitReadableCode', models.IntegerField(verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_docente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_linguagem', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('conceitos_aplicados', models.TextField(blank=True)),
                ('tecnologias_usadas', models.TextField(blank=True)),
                ('imagem', models.ImageField(null=True, upload_to='')),
                ('link_youtube', models.URLField(null=True)),
                ('link_github', models.URLField(null=True)),
            ],
        ),
    ]
