# Generated by Django 4.0.6 on 2024-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='conceitos_aplicados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias_usadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
