# Generated by Django 4.0.6 on 2024-04-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_projeto_conceitos_aplicados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='cursos.areacientifica'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(related_name='disciplina', to='cursos.linguagem'),
        ),
        migrations.AddField(
            model_name='docente',
            name='disciplinas',
            field=models.ManyToManyField(related_name='docentes', to='cursos.disciplina'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='disciplina',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto_disciplina', to='cursos.disciplina'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='linguagens',
            field=models.ManyToManyField(related_name='projetos_linguagem', to='cursos.linguagem'),
        ),
    ]
