# Generated by Django 4.0.6 on 2024-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_disciplina_area_cientifica_disciplina_linguagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='grau',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='numero_de_creditos',
            field=models.IntegerField(default=0, verbose_name='Número de créditos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='numero_de_semestres',
            field=models.IntegerField(default=0, verbose_name='Número de semestres'),
            preserve_default=False,
        ),
    ]
