# Generated by Django 4.0.6 on 2024-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_grau_curso_numero_de_creditos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curricularIUnitReadableCode',
            field=models.CharField(max_length=50),
        ),
    ]
