# Generated by Django 4.0.6 on 2024-04-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_disciplina_curriculariunitreadablecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='disciplinas',
            field=models.ManyToManyField(null=True, related_name='docentes', to='cursos.disciplina'),
        ),
    ]
