# Generated by Django 4.0.6 on 2024-04-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_docente_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='abreviatura',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo_do_cruso',
            field=models.IntegerField(null=True, verbose_name='Código do curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='cursos.disciplina'),
        ),
    ]
