# Generated by Django 4.0.6 on 2024-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_curso_abreviatura_curso_codigo_do_cruso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(max_length=50),
        ),
    ]
