# Generated by Django 4.0.6 on 2024-04-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_disciplina_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='conceitos_aplicados',
            new_name='conceitos',
        ),
    ]
