# Generated by Django 4.0.6 on 2024-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_rename_conceitos_aplicados_projeto_conceitos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='conceitos',
            new_name='conceitos_aplicados',
        ),
    ]
