# Generated by Django 4.0.6 on 2024-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_rename_conceitos_projeto_conceitos_aplicados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(null=True, related_name='disciplina', to='cursos.linguagem'),
        ),
    ]
