# Generated by Django 4.0.6 on 2024-04-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_alter_disciplina_linguagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo_do_cruso',
            new_name='codigo_do_curso',
        ),
    ]
