# Generated by Django 4.0.6 on 2024-05-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_rename_codigo_do_cruso_curso_codigo_do_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='cursos.curso'),
        ),
    ]
