# Generated by Django 4.0.6 on 2024-04-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='praia_fotos'),
        ),
    ]
