# Generated by Django 4.0.6 on 2024-04-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0003_remove_regiao_praia_regiao_praia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='praia',
        ),
        migrations.AddField(
            model_name='praia',
            name='servicos',
            field=models.ManyToManyField(related_name='praia', to='praias.servico'),
        ),
    ]
