# Generated by Django 4.0.6 on 2024-03-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banda', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(max_length=50, null=True)),
                ('ano_de_criacao', models.IntegerField(verbose_name='Ano de Criação')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('estilo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_musica', models.CharField(max_length=200)),
                ('duracao', models.IntegerField(verbose_name='Duração')),
                ('link', models.URLField(null=True)),
                ('data_lancamento', models.IntegerField(verbose_name='Lançamento')),
                ('banda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_da_banda_na_musica', to='bandas.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_album', models.CharField(max_length=200)),
                ('capa', models.ImageField(null=True, upload_to='')),
                ('ano_de_lancamento', models.IntegerField(verbose_name='Ano de Lançamento')),
                ('duracao_album', models.IntegerField(null=True, verbose_name='Duração')),
                ('banda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_da_banda', to='bandas.banda')),
                ('musica', models.ManyToManyField(related_name='album', to='bandas.musica')),
            ],
        ),
    ]
