# Generated by Django 4.0.6 on 2024-03-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_alter_banda_ano_de_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='data_lancamento',
            field=models.IntegerField(null=True, verbose_name='Lançamento'),
        ),
    ]
