# Generated by Django 4.0.6 on 2024-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_alter_banda_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/banda_fotos'),
        ),
    ]
