# Generated by Django 4.0.6 on 2024-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0010_alter_musica_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.IntegerField(null=True, verbose_name='Duração'),
        ),
    ]
