# Generated by Django 4.0.6 on 2024-04-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
