# Generated by Django 4.0.6 on 2024-04-20 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_artigo_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('numero', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='artigos.artigo')),
                ('autor_do_rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='artigos.utilizador')),
            ],
        ),
    ]
