# Generated by Django 4.0.6 on 2024-04-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='preview_review',
            field=models.CharField(default='n/a', max_length=150),
            preserve_default=False,
        ),
    ]
