# Generated by Django 4.0.6 on 2024-04-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_review_preview_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='autor_do_rating',
            new_name='utilizador',
        ),
    ]
