# Generated by Django 4.0.6 on 2024-05-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0005_rename_autor_do_rating_review_utilizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='artigos.utilizador'),
        ),
    ]
