# Generated by Django 4.0.6 on 2024-05-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0006_alter_review_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='utilizador',
        ),
        migrations.AddField(
            model_name='review',
            name='utilizador',
            field=models.ManyToManyField(related_name='review', to='artigos.utilizador'),
        ),
    ]
