# Generated by Django 4.0.6 on 2024-05-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0008_remove_review_utilizador_review_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='utilizador',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizador', to='artigos.review'),
        ),
    ]
