# Generated by Django 4.0.6 on 2024-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0010_remove_utilizador_reviews_review_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='blognest_fotos'),
        ),
    ]
